// Mocks generated by Mockito 5.4.6 from annotations
// in charge_locations_app/test/presentation/blocs/search/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:charge_locations_app/data/local/local_cache_service.dart'
    as _i3;
import 'package:charge_locations_app/data/models/charge_location.dart' as _i6;
import 'package:charge_locations_app/domain/repositories/charge_location_repository.dart'
    as _i2;
import 'package:charge_locations_app/domain/usecases/cached_locations_usecase.dart'
    as _i7;
import 'package:charge_locations_app/domain/usecases/fetch_locations_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChargeLocationRepository_0 extends _i1.SmartFake
    implements _i2.ChargeLocationRepository {
  _FakeChargeLocationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalCacheService_1 extends _i1.SmartFake
    implements _i3.LocalCacheService {
  _FakeLocalCacheService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchLocationsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchLocationsUsecase extends _i1.Mock
    implements _i4.FetchLocationsUsecase {
  MockFetchLocationsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChargeLocationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChargeLocationRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChargeLocationRepository);

  @override
  _i5.Future<List<_i6.ChargeLocation>> call(String? city) =>
      (super.noSuchMethod(
            Invocation.method(#call, [city]),
            returnValue: _i5.Future<List<_i6.ChargeLocation>>.value(
              <_i6.ChargeLocation>[],
            ),
          )
          as _i5.Future<List<_i6.ChargeLocation>>);
}

/// A class which mocks [CachedLocationsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCachedLocationsUsecase extends _i1.Mock
    implements _i7.CachedLocationsUsecase {
  MockCachedLocationsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LocalCacheService get cacheService =>
      (super.noSuchMethod(
            Invocation.getter(#cacheService),
            returnValue: _FakeLocalCacheService_1(
              this,
              Invocation.getter(#cacheService),
            ),
          )
          as _i3.LocalCacheService);

  @override
  _i5.Future<List<_i6.ChargeLocation>?> getLastCachedLocations() =>
      (super.noSuchMethod(
            Invocation.method(#getLastCachedLocations, []),
            returnValue: _i5.Future<List<_i6.ChargeLocation>?>.value(),
          )
          as _i5.Future<List<_i6.ChargeLocation>?>);

  @override
  _i5.Future<void> saveLastSearch(String? city, List<dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveLastSearch, [city, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
